theme = "annaengeln"
languageCode = "de-de"
baseURL = "http://annanengeln.github.io/"
title = "Anna Engeln"
author = "Anna Engeln"
copyright = "Copyright Â© 2022, Anna Engeln"

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

disableKinds = ["taxonomy", "taxonomyTerm"]

enableRobotsTXT = true

[params]
    name = "Anna Engeln"
    description = "A simple bootstraped theme for Hugo, built with Tailwindcss."

    github_user = "annaengeln"
    github_repo = "https://github.com/annaengeln/annaengeln.github.io"
    github_banner = true

    favicon = "favicon.png"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5